import os


class FilePaths:
    """
    Consists of getters of project files
    """
    __SETTINGS_FILE_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "user_fonts.json"))

    __THEMES_FILEPATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "themes.json"))
    __LOGO_FILEPATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "window_logo.ico"))

    @property
    def settings_filepath(self):
        return self.__SETTINGS_FILE_PATH

    @property
    def themes_filepath(self):
        return self.__THEMES_FILEPATH

    @property
    def logo_filepath(self):
        return self.__LOGO_FILEPATH


class AvailableFonts:
    @staticmethod
    def get() -> tuple:
        return (
            "System",
            "Terminal",
            "Fixedsys",
            "Modern",
            "Roman",
            "Script",
            "Courier",
            "MS Serif",
            "MS Sans Serif",
            "Small Fonts",
            "Marlett",
            "Arial",
            "Arabic Transparent",
            "Arial Baltic",
            "Arial CE",
            "Arial CYR",
            "Arial Greek",
            "Arial TUR",
            "Arial Black",
            "Bahnschrift Light",
            "Bahnschrift SemiLight",
            "Bahnschrift",
            "Bahnschrift SemiBold",
            "Bahnschrift Light SemiCondensed",
            "Bahnschrift SemiLight SemiCondensed",
            "Bahnschrift SemiCondensed",
            "Bahnschrift SemiBold SemiCondensed",
            "Bahnschrift Light Condensed",
            "Bahnschrift SemiLight Condensed",
            "Bahnschrift Condensed",
            "Bahnschrift SemiBold Condensed",
            "Calibri",
            "Calibri Light",
            "Cambria",
            "Cambria Math",
            "Candara",
            "Candara Light",
            "Comic Sans MS",
            "Consolas",
            "Constantia",
            "Corbel",
            "Corbel Light",
            "Courier New",
            "Courier New Baltic",
            "Courier New CE",
            "Courier New CYR",
            "Courier New Greek",
            "Courier New TUR",
            "Ebrima",
            "Franklin Gothic Medium",
            "Gabriola",
            "Gadugi",
            "Georgia",
            "HoloLens MDL2 Assets",
            "Impact",
            "Ink Free",
            "Javanese Text",
            "Leelawadee UI",
            "Leelawadee UI Semilight",
            "Lucida Console",
            "Lucida Sans Unicode",
            "Malgun Gothic",
            "@Malgun Gothic",
            "Malgun Gothic Semilight",
            "@Malgun Gothic Semilight",
            "Microsoft Himalaya",
            "Microsoft JhengHei",
            "@Microsoft JhengHei",
            "Microsoft JhengHei UI",
            "@Microsoft JhengHei UI",
            "Microsoft JhengHei Light",
            "@Microsoft JhengHei Light",
            "Microsoft JhengHei UI Light",
            "@Microsoft JhengHei UI Light",
            "Microsoft New Tai Lue",
            "Microsoft PhagsPa",
            "Microsoft Sans Serif",
            "Microsoft Tai Le",
            "Microsoft YaHei",
            "@Microsoft YaHei",
            "Microsoft YaHei UI",
            "@Microsoft YaHei UI",
            "Microsoft YaHei Light",
            "@Microsoft YaHei Light",
            "Microsoft YaHei UI Light",
            "@Microsoft YaHei UI Light",
            "Microsoft Yi Baiti",
            "MingLiU-ExtB",
            "@MingLiU-ExtB",
            "PMingLiU-ExtB",
            "@PMingLiU-ExtB",
            "MingLiU_HKSCS-ExtB",
            "@MingLiU_HKSCS-ExtB",
            "Mongolian Baiti",
            "MS Gothic",
            "@MS Gothic",
            "MS UI Gothic",
            "@MS UI Gothic",
            "MS PGothic",
            "@MS PGothic",
            "MV Boli",
            "Myanmar Text",
            "Nirmala UI",
            "Nirmala UI Semilight",
            "Palatino Linotype",
            "Segoe MDL2 Assets",
            "Segoe Print",
            "Segoe Script",
            "Segoe UI",
            "Segoe UI Black",
            "Segoe UI Emoji",
            "Segoe UI Historic",
            "Segoe UI Light",
            "Segoe UI Semibold",
            "Segoe UI Semilight",
            "Segoe UI Symbol",
            "SimSun",
            "@SimSun",
            "NSimSun",
            "@NSimSun",
            "SimSun-ExtB",
            "@SimSun-ExtB",
            "Sitka Small",
            "Sitka Text",
            "Sitka Subheading",
            "Sitka Heading",
            "Sitka Display",
            "Sitka Banner",
            "Sylfaen",
            "Symbol",
            "Tahoma",
            "Times New Roman",
            "Times New Roman Baltic",
            "Times New Roman CE",
            "Times New Roman CYR",
            "Times New Roman Greek",
            "Times New Roman TUR",
            "Trebuchet MS",
            "Verdana",
            "Webdings",
            "Wingdings",
            "Yu Gothic",
            "@Yu Gothic",
            "Yu Gothic UI",
            "@Yu Gothic UI",
            "Yu Gothic UI Semibold",
            "@Yu Gothic UI Semibold",
            "Yu Gothic Light",
            "@Yu Gothic Light",
            "Yu Gothic UI Light",
            "@Yu Gothic UI Light",
            "Yu Gothic Medium",
            "@Yu Gothic Medium",
            "Yu Gothic UI Semilight",
            "@Yu Gothic UI Semilight"
        )
